### ISSUE TITLE
大疆 RoboMaster 机甲大师开通 ”机甲小 S 实验室”知乎专栏

### ISSUE THREAD

**Issue by nobodxbodon** [open-ai-robot/awesome-dji-robomaster#4]
专栏地址： [机甲小 S 实验室](https://zhuanlan.zhihu.com/c_1175002569993388032)

**Comment by unbug** [comment]
@nobodxbodon 你是大疆的？

**Comment by nobodxbodon** [comment]
并不是呵。

**Comment by nobodxbodon** [comment]
@unbug 专栏是[官方](https://www.zhihu.com/org/robomasters/activities)开的。我只是被邀请为了作者。

**Comment by unbug** [comment]
@nobodxbodon 赞赞赞
